### PR TITLE
Section 11

### PR DESCRIPTION
**Pull request by uo282892**
# Changes

 Section 11 (Risks and technical debts) for the first phase of the documentation has been filled.

### CODE REVIEW

**Review by Davidmc07 — APPROVED** [review]

**Comment by UO283428** [comment]
Everything correct.

**Review by UO283428 — APPROVED** [review]
All correct.

**Review by Pelayo-Reguera — CHANGES_REQUESTED** [review]
I think the firts row of section "Risks" should be part of "Technical debts" (the one about "Steep technology learning curve"). In addition to this technical debt, I think we should include the use of Resource Description Framework as it is the standard format in which the documents should be stored in PODs.

**Comment by Davidmc07** [comment]
The learning curve is a risk since it may arise problems but they have not happened yet.

**Comment by uo282892** [comment]
> I think the firts row of section "Risks" should be part of "Technical debts" (the one about "Steep technology learning curve"). In addition to this technical debt, I think we should include the use of Resource Description Framework as it is the standard format in which the documents should be stored in PODs.

I will check

**Review by Pelayo-Reguera — APPROVED** [review]
Now I agree

**Comment by uo282892** [comment]
> > I think the firts row of section "Risks" should be part of "Technical debts" (the one about "Steep technology learning curve"). In addition to this technical debt, I think we should include the use of Resource Description Framework as it is the standard format in which the documents should be stored in PODs.
> 
> I will check

I added RDF as you suggested. However, there is no technical debt to register at the moment, as thew will arise once we start implementing.

**Review by UO283069 — APPROVED** [review]

**Pull request merged**
