### PR TITLE
60 image delete function not working

### PR DESCRIPTION
**Pull request by UO283428**
The function for deleting images works again. Now it is not possible to add an already added photo, the button to clear images only appears once more than one photo is added. Colors have been adapted. Errors are now showned as read messages below.

image
image
image
image

The functionality for adding categories to places is also implemented.

### CODE REVIEW

**Review by uo282892 — CHANGES_REQUESTED** [review]
Change the destination branch to develop.

**Comment by UO283428** [comment]
> Change the destination branch to develop.

Hecho, gracias!!

**Review by uo282892 — APPROVED** [review]

**Review by UO283069 — APPROVED** [review]

**Review by Pelayo-Reguera — APPROVED** [review]
I think the enum class of categories may be exported to an external file but as you want. For the next delivery I also think that we can focus more on improving the aspect of that view instead of adding more features.

**Review by Davidmc07 — APPROVED** [review]
The conflicts have to be resolved in order to merge the branch. It could be better to extract the validations in AddPlace to a separate class, but for now it's ok

**Comment by UO283428** [comment]
> The conflicts have to be resolved in order to merge the branch. It could be better to extract the validations in AddPlace to a separate class, but for now it's ok

Yes, those conflicts appeared when you merged the pull request that was created after this one. I'll try to solve them.

**Comment by UO283428** [comment]
Due to other issuse, this pull request is no longer valid and will be closed.

**Pull request closed without merging**
