### PR TITLE
Fix section 8

### PR DESCRIPTION
**Pull request by UO283069**
Updated the Domain Model from Section 8 of the documentation.

### CODE REVIEW

**Review by uo282892 — CHANGES_REQUESTED** [review]
The attribute "friends" in user has a typo, and there is a "<<use>>" that is placed weirdly. Apartfrom that, I see no more issues

**Review by Pelayo-Reguera — APPROVED** [review]

**Comment by UO283069** [comment]
There is a "<<use>>" inside the PlaceManager that seems to be wrongly placed.

**Comment by uo282892** [comment]
> There is a "<>" inside the PlaceManager that seems to be wrongly placed.

Yes, this is what I was referring about in my previous comment. It is the only thing left to fix.

**Review by uo282892 — CHANGES_REQUESTED** [review]
Just remove the "<<use>>" at the right of PlaceManager and it will be ok.

**Review by uo282892 — APPROVED** [review]

**Pull request merged**
