### PR TITLE
Section 9 - Design decisions

### PR DESCRIPTION
**Pull request by Davidmc07**
Add the design decisions to the documentation.

Co-authored-by: Carlos Triana Fernández <UO283428@uniovi.es>

### CODE REVIEW

**Review by UO283069 — APPROVED** [review]

**Review by uo282892 — COMMENTED** [review]
What does it mean "Status: Accepted" on line 17?

**Review by UO283428 — APPROVED** [review]
All correct.

**Comment by Davidmc07** [comment]
> What does it mean "Status: Accepted" on line 17?

The status of the decision. It can be proposed, accepted or superseded.

**Comment by uo282892** [comment]
> > What does it mean "Status: Accepted" on line 17?
> 
> The status of the decision. It can be proposed, accepted or superseded.

Now I understand.

**Review by uo282892 — APPROVED** [review]

**Pull request merged**
