### PR TITLE
Documentation for section 5 has been added.

### PR DESCRIPTION
**Pull request by UO283069**
Documentation for section 5.Building Block View for the first deriverable of the Documentation done.

### CODE REVIEW

**Review by Davidmc07 — CHANGES_REQUESTED** [review]
I think that the motivation should be removed.

**Review by UO283428 — APPROVED** [review]
All correct.

**Review by Davidmc07 — APPROVED** [review]

**Review by uo282892 — APPROVED** [review]
Everything seems okay.

**Review by uo282892 — CHANGES_REQUESTED** [review]
I think you will delete other files

(My bad, I saw it wrong)

**Review by uo282892 — APPROVED** [review]

**Review by Davidmc07 — APPROVED** [review]

**Pull request merged**
